config/routes.rb
Rails.application.routes.draw do

  resources :members
  resource :session

  resources :propositions do
    resources :arguments
  end
  resources :perspectives
  resources :questions do
    resources :answers
  end
end

app/models/acceptance_relation.rb
class AcceptanceRelation < ApplicationRecord
  belongs_to :perspective
  belongs_to :proposition
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :reference, polymorphic: true

  validates_presence_of :reference
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  default_scope { order(id: :asc) }
end

app/models/argument.rb
class Argument < ApplicationRecord
  belongs_to :subject, polymorphic: true

  enum type: {support: 0, attack: 1}
  self.inheritance_column = nil
end

app/models/candidate_relation.rb
class CandidateRelation < ApplicationRecord
  belongs_to :dependency
  belongs_to :proposition
end

app/models/dependency.rb
class Dependency < ApplicationRecord
  belongs_to :proposition
  has_many :candidate_relations
  has_many :candidates, through: :candidate_relations, source: :proposition

  validates_presence_of :title
end

app/models/member.rb
class Member < ApplicationRecord
  has_secure_password
end

app/models/objection.rb
class Objection < ApplicationRecord
  belongs_to :theory
end

app/models/perspective.rb
class Perspective < ApplicationRecord
  has_many :acceptance_relations
  has_many :accepted_propositions, through: :acceptance_relations, source: :proposition

  validates_presence_of :title
end

app/models/proposition.rb
class Proposition < ApplicationRecord
  has_many :dependencies
  has_many :arguments, as: :subject

  validates_presence_of :title
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/models/theory.rb
class Theory < ApplicationRecord
  has_many :objections
  has_many :answers

end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update]
  before_action :require_admin, only: [:new, :create, :edit, :update]

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/objections_helper.rb
module ObjectionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theories_helper.rb
module TheoriesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <div>
    Title: <%= f.text_field :title %>
  </div>
  <div>
    Body: <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<% @questions.each do |q| %>
  <div>
    <%= q.title %>
    <%= link_to 'show', question_path(q) %>
    <%= link_to 'edit', edit_question_path(q) %>
  </div>
<% end %>

<%= link_to 'new', new_question_path %>

app/views/questions/show.html.erb
<%= @question.title %>

<hr class="my-2">

<div>
  <%= simple_format @question.body %>
</div>

<hr class="my-2">

<div>
  <h2>Candidate answers</h2>
  <% @question.answers.each do |a| %>
    <div>
      <%= a.reference.title %>
      <%= link_to 'show', question_answer_path(a) %>
      <%= link_to 'edit', edit_question_answer_path(a) %>
    </div>
  <% end %>
</div>

<%= link_to 'new', new_question_answer_path(@question) %>

<%= link_to 'back to question list', questions_path %>