config/routes.rb
Rails.application.routes.draw do

  resources :members
  resource :session

  resources :propositions do
    resources :arguments
  end
  resources :perspectives
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :reference, polymorphic: true

  validates_presence_of :reference
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  default_scope { order(id: :asc) }
end

app/models/argument.rb
class Argument < ApplicationRecord
  belongs_to :subject, polymorphic: true

  enum type: {support: 0, attack: 1}
  self.inheritance_column = nil
end

app/models/candidate_relation.rb
class CandidateRelation < ApplicationRecord
  belongs_to :dependency
  belongs_to :proposition
end

app/models/dependency.rb
class Dependency < ApplicationRecord
  belongs_to :proposition
  has_many :candidate_relations
  has_many :candidates, through: :candidate_relations, source: :proposition

  validates_presence_of :title
end

app/models/member.rb
class Member < ApplicationRecord
  has_secure_password
end

app/models/objection.rb
class Objection < ApplicationRecord
  belongs_to :theory
end

app/models/perspective.rb
class Perspective < ApplicationRecord
  has_many :acceptance_relations
  has_many :accepted_propositions, through: :acceptance_relations, source: :proposition

  validates_presence_of :title
end

app/models/proposition.rb
class Proposition < ApplicationRecord
  has_many :dependencies
  has_many :arguments, as: :subject

  validates_presence_of :title
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/models/theory.rb
class Theory < ApplicationRecord
  has_many :objections
  has_many :answers

end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/propositions_controller.rb
class PropositionsController < ApplicationController
  before_action :set_proposition, only: [:show, :edit, :update]
  before_action :require_admin, only: [:new, :create, :edit, :update]

  def index
    @propositions = Proposition.all
  end

  def show
  end

  def new
    @proposition = Proposition.new
  end

  def create
    @proposition = Proposition.new(proposition_params)

    if @proposition.save
      redirect_to proposition_path(@proposition)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @proposition.update(proposition_params)
      redirect_to proposition_path(@proposition)
    else
      render :edit
    end
  end

  private
    def set_proposition
      @proposition = Proposition.find(params[:id])
    end

    def proposition_params
      params.require(:proposition).permit(:title, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/objections_helper.rb
module ObjectionsHelper
end

app/helpers/propositions_helper.rb
module PropositionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theories_helper.rb
module TheoriesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/propositions/_form.html.erb
<%= form_with model: @proposition do |f| %>
  <div>
    Title: <%= f.text_field :title %>
  </div>
  <div>
    Body: <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/propositions/index.html.erb
<% @propositions.each do |p| %>
  <div>
    <%= p.title %>
    <%= link_to 'show', proposition_path(p) %>
    <%= link_to 'edit', edit_proposition_path(p) %>
  </div>
<% end %>

<%= link_to 'new', new_proposition_path %>

app/views/propositions/show.html.erb
<%= @proposition.title %>

<hr class="my-2">

<div>
  <%= simple_format @proposition.body %>
</div>

<hr class="my-2">

<div>
  <h2>Dependencies</h2>
  <% @proposition.dependencies.each do |d| %>
    <div>
      <%= d.title %>
    </div>
  <% end %>
</div>

<hr class="my-2">

<div>
  <h2>Arguments</h2>
  <% @proposition.arguments.each do |a| %>
    <div>
      <%= a.type %> argument:
      <%= a.title %>
      <%= link_to 'show', proposition_argument_path(@proposition, a) %>
      <%= link_to 'edit', edit_proposition_argument_path(@proposition, a) %>
    </div>
  <% end %>
  <%= link_to 'new', new_proposition_argument_path(@proposition) %>
</div>

<hr class="my-2">

<%= link_to 'back to proposition list', propositions_path %>